[workspace]
resolver = "2"
members = [
    "jellyfin-rpc",
    "jellyfin-rpc-cli",
    "jellyfin-rpc-gui",
    #"jftest", # Used for local testing
]

default-members = [
    "jellyfin-rpc",
    "jellyfin-rpc-cli",
    "jellyfin-rpc-gui",
]

[profile.release]
strip = true
lto = true
codegen-units = 1
panic = "abort"
